SET:
- Batch_size: 32
  Boundary: 1100,550,550,400
  Con_record: 0,2000,5000
  Domain_Numbers: 2400
  Epoch: 5200
  Model: mscalenn2
  Mu: 7
  Note: note
  PDE_Solver: src_lam/possion_domain.py
  Penalty: 1000
  SEED: 1
  Save_Path: Result/Expr2_1
  Scale_Coeff: 1,4,8,16,32
  Sub_number: 1
  Sum_Samples: 5000
  Test_Dataset: data/possion_2d/holes/test_loader.pt
  Train_Dataset: data/possion_2d/holes/train_loader.pt
  Valid_Dataset: data/possion_2d/holes/val_loader.pt
  lr: 0.0001
Subnet1:
- Act_Set: phi,phi,phi
  Ini_Set: xavier_uniform
  Layer_Set: 2,200,200,200,1
  Residual: false
Subnet2:
- Act_Set: phi,phi,phi
  Ini_Set: xavier_uniform
  Layer_Set: 2,200,200,200,1
  Residual: false
Subnet3:
- Act_Set: phi,phi,phi
  Ini_Set: xavier_uniform
  Layer_Set: 2,200,200,200,1
  Residual: false
Subnet4:
- Act_Set: phi,phi,phi
  Ini_Set: xavier_uniform
  Layer_Set: 2,200,200,200,1
  Residual: false
Subnet5:
- Act_Set: phi,phi,phi
  Ini_Set: xavier_uniform
  Layer_Set: 2,200,200,200,1
  Residual: false
