SET:
- Batch_size: 1
  Epoch: 5000
  Model: mscalenn2
  Note: note
  SEED: 1
  Save_Path: Result/Expr1_
  Scale_Coeff: 10000,10,100,1000
  Sub_number: 4
  Test_Dataset: data/freq_1d/mu_100/test_loader.pt
  Train_Dataset: data/freq_1d/mu_100/train_loader.pt
  Valid_Dataset: data/freq_1d/mu_100/val_loader.pt
  lr: 0.0001
Subnet1:
- Act_Set: phi,phi,phi
  Ini_Set: xavier_uniform
  Layer_Set: 1,10,10,10,1
  Residual: false
Subnet2:
- Act_Set: phi,phi,phi
  Ini_Set: xavier_uniform
  Layer_Set: 1,10,10,10,1
  Residual: false
Subnet3:
- Act_Set: phi,phi,phi
  Ini_Set: xavier_uniform
  Layer_Set: 1,10,10,10,1
  Residual: false
Subnet4:
- Act_Set: phi,phi,phi
  Ini_Set: xavier_uniform
  Layer_Set: 1,10,10,10,1
  Residual: false
