SET:
- Batch_size: 32
  Epoch: 5000
  Model: mscalenn2
  Note: note
  SEED: 1
  Save_Path: Result/Expr1_4
  Scale_Coeff: 32
  Sub_number: 1
  Test_Dataset: data/freq_1d/mu_70/test_loader.pt
  Train_Dataset: data/freq_1d/mu_70/train_loader.pt
  Valid_Dataset: data/freq_1d/mu_70/val_loader.pt
  lr: 0.001
Subnet1:
- Act_Set: phi,phi,phi
  Ini_Set: xavier_uniform
  Layer_Set: 1,150,150,150,1
  Residual: false
