SET:
- Batch_size: 256
  Con_record: 0,2000,5000
  Epoch: 5200
  Model: mscalenn2
  Note: note
  SEED: 1
  Save_Path: Result/Expr1_2
  Scale_Coeff: 16
  Sub_number: 4
  Test_Dataset: data/freq_1d/mu_70/test_loader.pt
  Train_Dataset: data/freq_1d/mu_70/train_loader.pt
  Valid_Dataset: data/freq_1d/mu_70/val_loader.pt
  lr: 0.001
Subnet1:
- Act_Set: phi,phi,phi
  Ini_Set: xavier_uniform
  Layer_Set: 1,150,150,150,1
  Residual: false
